### ISSUE TITLE
Sometimes characters are removed from the font

### ISSUE THREAD

**Issue by LettError** [LettError/glyphBrowser#14]
Aleksi will show me an example.

**Comment by alexisbosc** [comment]
Actually now with the last update the extension doesn’t want to start

`Traceback (most recent call last):
​  File "browser.py", line 1286, in <module>
  File "browser.py", line 889, in __init__
TypeError: __init__() got an unexpected keyword argument 'menuCallback'`

**Comment by alexisbosc** [comment]
It’s the 2.5.6

**Comment by LettError** [comment]
Your RF version? :)

**Comment by alexisbosc** [comment]
The last one I think, 3.1!

**Comment by alexisbosc** [comment]
Thanks Erik!
